// client/src/components/chat/MessageInput.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useWebSocketStore } from '@/stores/webSocketStore';
import { useMessageStore } from '@/stores/messageStore';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

const webSocketStore = useWebSocketStore();
const messageStore = useMessageStore();

const messageInput = ref('');
const isSending = ref(false);

async function handleSend() {
  if (!messageInput.value.trim() || isSending.value) return;

  isSending.value = true;
  try {
    await messageStore.sendMessage(messageInput.value);
    messageInput.value = '';
  } catch (error) {
    console.error('Failed to send message:', error);
  } finally {
    isSending.value = false;
  }
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    handleSend();
  }
}
</script>

<template>
  <div class="p-4 border-t">
    <div class="flex gap-2">
      <Input
        v-model="messageInput"
        placeholder="Type a message..."
        :disabled="!webSocketStore.isConnected || isSending"
        @keydown="handleKeydown"
        class="flex-1"
      />
      <Button
        @click="handleSend"
        :disabled="!webSocketStore.isConnected || isSending || !messageInput.trim()"
      >
        {{ isSending ? 'Sending...' : 'Send' }}
      </Button>
    </div>
  </div>
</template>

// client/src/components/chat/MessageInput.tsx
import { useState, useRef, type KeyboardEvent } from "react";
import { Paperclip } from "lucide-react";
import { Button } from "@/components/ui/button";

interface MessageInputProps {
  onSend: (content: string) => void;
}

export function MessageInput({ onSend }: MessageInputProps) {
  const [value, setValue] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  function handleSend() {
    const trimmed = value.trim();
    if (!trimmed) return;
    onSend(trimmed);
    setValue("");
    textareaRef.current?.focus();
  }

  function handleKeyDown(e: KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  }

  return (
    <div className="border-t px-4 py-3">
      <div className="flex items-end gap-2">
        <Button
          variant="ghost"
          size="icon"
          className="shrink-0 text-muted-foreground"
          title="Attach file"
        >
          <Paperclip className="h-4 w-4" />
        </Button>
        <textarea
          ref={textareaRef}
          value={value}
          onChange={(e) => setValue(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type a message..."
          rows={1}
          className="flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none placeholder:text-muted-foreground"
        />
        <Button
          variant="ghost"
          onClick={handleSend}
          disabled={!value.trim()}
          className="shrink-0 font-semibold text-primary hover:text-primary"
        >
          Send message
        </Button>
      </div>
    </div>
  );
}
