// client/src/components/MessageBubble.tsx
import type { Message } from '@/types';
import { Avatar } from '@/components/ui/avatar';
import { formatMessageTime } from '@/lib/dateUtils';
import { cn } from '@/lib/utils';

interface MessageBubbleProps {
  message: Message;
  isCurrentUser: boolean;
  showAvatar?: boolean;
}

export function MessageBubble({
  message,
  isCurrentUser,
  showAvatar = true,
}: MessageBubbleProps) {
  return (
    <div
      className={cn(
        'flex gap-3 mb-4',
        isCurrentUser ? 'flex-row-reverse' : 'flex-row'
      )}
    >
      {showAvatar ? (
        <Avatar className="h-8 w-8">
          <div className="h-full w-full bg-primary/10 flex items-center justify-center text-primary text-sm font-semibold">
            {message.sender_id[0]?.toUpperCase()}
          </div>
        </Avatar>
      ) : (
        <div className="h-8 w-8" /> // Spacer to maintain alignment
      )}

      <div
        className={cn(
          'flex flex-col gap-1 max-w-[70%]',
          isCurrentUser ? 'items-end' : 'items-start'
        )}
      >
        <div
          className={cn(
            'px-4 py-2 rounded-2xl',
            isCurrentUser
              ? 'bg-primary text-primary-foreground'
              : 'bg-muted text-foreground'
          )}
        >
          <p className="text-sm whitespace-pre-wrap wrap-break-word">
            {message.content}
          </p>
        </div>
        <span className="text-xs text-muted-foreground px-2">
          {formatMessageTime(message.created_at)}
        </span>
      </div>
    </div>
  );
}

// client/src/components/chat/MessageBubble.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useAuthStore } from '@/stores/authStore';
import { Card, CardContent } from '@/components/ui/card';
import type { Message } from '@/types';

const props = defineProps<{
  message: Message;
}>();

const authStore = useAuthStore();

const isOwnMessage = computed(() => {
  return props.message.sender_id === authStore.currentUser?.id;
});

const formattedTime = computed(() => {
  const date = new Date(props.message.created_at);
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
});
</script>

<template>
  <div class="flex" :class="isOwnMessage ? 'justify-end' : 'justify-start'">
    <div class="max-w-[70%]">
      <Card
        :class="
          isOwnMessage ? 'bg-primary text-primary-foreground' : 'bg-muted'
        "
      >
        <CardContent class="p-3">
          <p class="text-sm whitespace-pre-wrap wrap-break-word">
            {{ message.content }}
          </p>
          <div class="flex items-center justify-end gap-2 mt-1">
            <span class="text-xs opacity-70">{{ formattedTime }}</span>
            <span v-if="isOwnMessage" class="text-xs opacity-70">
              <!--TODO: May need to add message status to v-if at some point {{ message.status === 'sending' ? '⏳' : '✓' }} -->
            </span>
          </div>
        </CardContent>
      </Card>
    </div>
  </div>
</template>
