// client/src/components/MessageInput.tsx
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Send } from 'lucide-react';

interface MessageInputProps {
  onSend: (content: string) => void;
  disabled?: boolean;
}

export function MessageInput({ onSend, disabled = false }: MessageInputProps) {
  const [inputValue, setInputValue] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (inputValue.trim() && !disabled) {
      onSend(inputValue.trim());
      setInputValue('');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="border-t border-border p-4">
      <div className="flex gap-2">
        <Input
          type="text"
          placeholder="Type a message..."
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={disabled}
          className="flex-1"
        />
        <Button
          type="submit"
          disabled={!inputValue.trim() || disabled}
          size="icon"
        >
          <Send className="h-4 w-4" />
        </Button>
      </div>
    </form>
  );
}

// client/src/components/chat/MessageInput.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useWebSocketStore } from '@/stores/webSocketStore';
import { useMessageStore } from '@/stores/messageStore';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

const webSocketStore = useWebSocketStore();
const messageStore = useMessageStore();

const messageInput = ref('');
const isSending = ref(false);

async function handleSend() {
  if (!messageInput.value.trim() || isSending.value) return;

  isSending.value = true;
  try {
    await messageStore.sendMessage(messageInput.value);
    messageInput.value = '';
  } catch (error) {
    console.error('Failed to send message:', error);
  } finally {
    isSending.value = false;
  }
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    handleSend();
  }
}
</script>

<template>
  <div class="p-4 border-t">
    <div class="flex gap-2">
      <Input
        v-model="messageInput"
        placeholder="Type a message..."
        :disabled="!webSocketStore.isConnected || isSending"
        @keydown="handleKeydown"
        class="flex-1"
      />
      <Button
        @click="handleSend"
        :disabled="!webSocketStore.isConnected || isSending || !messageInput.trim()"
      >
        {{ isSending ? 'Sending...' : 'Send' }}
      </Button>
    </div>
  </div>
</template>
