// client/src/components/chat/ChatHeader.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useAuthStore } from '@/stores/authStore';
import { useWebSocketStore } from '@/stores/webSocketStore';
import Avatar from '../common/Avatar.vue';
import { Separator } from '@/components/ui/separator';
import type { Conversation } from '@/types';

const props = defineProps<{
  conversation: Conversation;
}>();

const authStore = useAuthStore();
const webSocketStore = useWebSocketStore();

const otherParticipant = computed(() => {
  return props.conversation.participants.find(
    (p) => p !== authStore.currentUser?.id
  );
});

const connectionStatusText = computed(() => {
  switch (webSocketStore.connectionStatus) {
    case 'connected':
      return 'Connected';
    case 'connecting':
      return 'Connecting...';
    case 'error':
      return 'Connection error';
    default:
      return 'Disconnected';
  }
});

const connectionStatusColor = computed(() => {
  return webSocketStore.isConnected ? 'bg-green-500' : 'bg-red-500';
});
</script>

<template>
  <div>
    <div class="p-4 flex items-center gap-3">
      <Avatar v-if="otherParticipant" :user="otherParticipant" size="md" />

      <div class="flex-1">
        <h2 class="font-semibold">
          {{ otherParticipant?.username || 'Unknown' }}
        </h2>
        <div class="flex items-center gap-2 text-xs text-muted-foreground">
          <div class="flex items-center gap-1">
            <div :class="['w-2 h-2 rounded-full', connectionStatusColor]" />
            <span>{{ connectionStatusText }}</span>
          </div>
        </div>
      </div>
    </div>
    <Separator />
  </div>
</template>

// client/src/components/ChatHeader.tsx
import type { Conversation } from '@/types';
import { Avatar } from '@/components/ui/avatar';
import { Separator } from '@/components/ui/separator';

interface ChatHeaderProps {
  conversation: Conversation;
  currentUserId: string;
}

export function ChatHeader({ conversation, currentUserId }: ChatHeaderProps) {
  // Get conversation title - use title for groups, or participant username for direct chats
  const getTitle = () => {
    if (conversation.title) {
      return conversation.title;
    }
    // For direct chats, show the other participant's ID (will be username in real app)
    const otherParticipant = conversation.participants.find(
      (p) => p !== currentUserId
    );
    return otherParticipant || 'Unknown';
  };

  const title = getTitle();
  const participantCount = conversation.participants.length;
  const isGroup = conversation.type === 'group';

  return (
    <>
      <div className="p-4 flex items-center gap-3">
        <Avatar className="h-10 w-10">
          <div className="h-full w-full bg-primary/10 flex items-center justify-center text-primary font-semibold">
            {title[0]?.toUpperCase()}
          </div>
        </Avatar>
        <div className="flex-1 min-w-0">
          <h2 className="font-semibold truncate">{title}</h2>
          <p className="text-sm text-muted-foreground">
            {isGroup ? `${participantCount} participants` : 'Online'}
          </p>
        </div>
      </div>
      <Separator />
    </>
  );
}
